# Generated by Django 5.0.6 on 2024-09-25 05:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TimedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=255)),
                ('viaje', models.IntegerField()),
                ('agrupacion', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('velocidad', models.FloatField()),
                ('distancia_acumulada', models.FloatField()),
                ('emocion', models.CharField(max_length=255)),
                ('id_poligono', models.IntegerField()),
                ('contexto_1', models.CharField(max_length=255)),
                ('contexto_2', models.CharField(max_length=255)),
                ('contexto_3', models.CharField(max_length=255)),
                ('SCL', models.FloatField()),
                ('SCR', models.FloatField()),
                ('SKT', models.FloatField()),
                ('MOS', models.FloatField(blank=True, null=True)),
                ('Peak_SCR', models.FloatField()),
            ],
        ),
    ]
